//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtualFinal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        public CONTRATO()
        {
            this.PRODUCTOR = new HashSet<PRODUCTOR>();
        }
    
        public decimal CONTRATO_ID { get; set; }
        public string CONTRATO_TIPO { get; set; }
        public string CONTRATO_INI { get; set; }
        public string CONTRATO_FIN { get; set; }
    
        public virtual ICollection<PRODUCTOR> PRODUCTOR { get; set; }
    }
}
