//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtualFinal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        public PEDIDO()
        {
            this.CLIENTEI = new HashSet<CLIENTEI>();
            this.CLIENTEX = new HashSet<CLIENTEX>();
            this.COMPRA = new HashSet<COMPRA>();
            this.SUBASTA = new HashSet<SUBASTA>();
        }
    
        public decimal PEDIDO_ID { get; set; }
        public string PEDIDO_TIPO { get; set; }
        public string PEDIDO_DATOS { get; set; }
        public string PEDIDO_DESTINO { get; set; }
        public Nullable<decimal> PRODUCTO_ID { get; set; }
    
        public virtual ICollection<CLIENTEI> CLIENTEI { get; set; }
        public virtual ICollection<CLIENTEX> CLIENTEX { get; set; }
        public virtual ICollection<COMPRA> COMPRA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual ICollection<SUBASTA> SUBASTA { get; set; }
    }
}
