//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtualFinal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOR
    {
        public PRODUCTOR()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public decimal PRODUCTOR_ID { get; set; }
        public string PRODUCTOR_NOMB { get; set; }
        public string PRODUCTOR_RUT { get; set; }
        public string PRODUCTOR_DIREC { get; set; }
        public string PRODUCTOR_TELEF { get; set; }
        public string PRODUCTOR_MEIL { get; set; }
        public Nullable<decimal> CONTRATO_ID { get; set; }
    
        public virtual CONTRATO CONTRATO { get; set; }
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
