//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtualFinal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public decimal PRODUCTO_ID { get; set; }
        public string PRODUCTO_NOMB { get; set; }
        public string PRODUCTO_DATOS { get; set; }
        public Nullable<decimal> PRODUCTO_PRECIO { get; set; }
        public Nullable<decimal> PRODUCTOR_ID { get; set; }
    
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
        public virtual PRODUCTOR PRODUCTOR { get; set; }
    }
}
