//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtualFinal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBASTA
    {
        public SUBASTA()
        {
            this.TRANSPORTISTA = new HashSet<TRANSPORTISTA>();
        }
    
        public decimal SUB_ID { get; set; }
        public string SUB_MINPESO { get; set; }
        public string SUB_MAXPESO { get; set; }
        public string SUB_DESCRIP { get; set; }
        public string SUB_ESTADO { get; set; }
        public string SUB_INI { get; set; }
        public string SUB_FIN { get; set; }
        public Nullable<decimal> PEDIDO_ID { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual ICollection<TRANSPORTISTA> TRANSPORTISTA { get; set; }
    }
}
