//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtualFinal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTISTA
    {
        public decimal TRANS_ID { get; set; }
        public string TRANS_NOMB { get; set; }
        public string TRANS_RUT { get; set; }
        public string TRANS_TELEF { get; set; }
        public string TRANS_MAIL { get; set; }
        public string TRANS_DIREC { get; set; }
        public string TRANS_MINPESO { get; set; }
        public string TRANS_MAXPESO { get; set; }
        public string TRANS_PATENTE { get; set; }
        public Nullable<decimal> SUB_ID { get; set; }
    
        public virtual SUBASTA SUBASTA { get; set; }
    }
}
